# https://github.com/kawasaki/pyscrlink

scratchlink:
	pipx install pyscrlink
	bluepy_helper_cap

scratch-microbit.hex.zip:
	wget https://downloads.scratch.mit.edu/microbit/$@

scratch-microbit-1.2.0.hex: scratch-microbit.hex.zip
	unzip $<
